/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bonsspassos.loja.home;

import com.bonsspassos.loja.cadastro.CadastroCliente;
import com.bonsspassos.loja.cadastro.CadastroProduto;
import com.bonsspassos.loja.consulta.ConsultaCliente;
import com.bonsspassos.loja.consulta.ConsultaProduto;
import com.bonsspassos.loja.relatorios.TelaRelatorio;
import com.bonsspassos.loja.vendas.TelaVenda;
import javax.swing.UIManager;

/**
 *
 * @author FernandoBindandi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        setExtendedState((int) CENTER_ALIGNMENT);
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroCalcados = new javax.swing.JMenuItem();
        cadastroClientes = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        ItemConsultaProdutos = new javax.swing.JMenuItem();
        ItemConsultaClientes = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bons Passos Calçados");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Bonspassos-logo.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));
        jMenuBar1.setToolTipText("");

        menuCadastro.setText("Cadastro");
        menuCadastro.setToolTipText("Cadastre clientes ou produtos");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadastroCalcados.setText("Calçados");
        cadastroCalcados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroCalcados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCalcadosActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCalcados);

        cadastroClientes.setText("Clientes");
        cadastroClientes.setToolTipText("Cadastro de clientes");
        cadastroClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroClientes);

        jMenuBar1.add(menuCadastro);

        menuConsulta.setText("Consultas");
        menuConsulta.setToolTipText("Consulte clientes ou produtos");
        menuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ItemConsultaProdutos.setText("Produtos");
        ItemConsultaProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultaProdutosActionPerformed(evt);
            }
        });
        menuConsulta.add(ItemConsultaProdutos);

        ItemConsultaClientes.setText("Clientes");
        ItemConsultaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultaClientesActionPerformed(evt);
            }
        });
        menuConsulta.add(ItemConsultaClientes);

        jMenuBar1.add(menuConsulta);

        menuVendas.setText("Vendas");
        menuVendas.setToolTipText("Realize uma venda");
        menuVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasActionPerformed(evt);
            }
        });

        menuItemVendas.setText("Realizar vendas");
        menuItemVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendasActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemVendas);

        jMenuBar1.add(menuVendas);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.setToolTipText("Acesse o relatório sintético ou analitico");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Gerar Relatório");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem1);

        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroCalcadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCalcadosActionPerformed
        // TODO add your handling code here:
        CadastroProduto telaCadastroProduto = new CadastroProduto();
        telaCadastroProduto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_cadastroCalcadosActionPerformed

    private void cadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClientesActionPerformed
        CadastroCliente telaCadastro = new CadastroCliente();
        telaCadastro.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_cadastroClientesActionPerformed

    private void menuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuVendasActionPerformed

    private void menuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendasActionPerformed
        // TODO add your handling code here:
        TelaVenda telaVenda = new TelaVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_menuItemVendasActionPerformed

    private void ItemConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultaClientesActionPerformed
        // TODO add your handling code here:
        ConsultaCliente telaConsultaCliente = new ConsultaCliente();
        telaConsultaCliente.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ItemConsultaClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaRelatorio telaRelatorio = new TelaRelatorio();
        telaRelatorio.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultaProdutosActionPerformed
        ConsultaProduto telaConsultaProduto = new ConsultaProduto();
        telaConsultaProduto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_ItemConsultaProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemConsultaClientes;
    private javax.swing.JMenuItem ItemConsultaProdutos;
    private javax.swing.JMenuItem cadastroCalcados;
    private javax.swing.JMenuItem cadastroClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuVendas;
    // End of variables declaration//GEN-END:variables
}
