package com.bonsspassos.loja.consulta;

import static com.bonsspassos.loja.consulta.ConsultaProduto.addProdutoTable;
import com.bonsspassos.loja.daos.DaoProduto;
import com.bonsspassos.loja.edicao.EditaProduto;
import com.bonsspassos.loja.model.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FernandoBindandi
 */
public class ConsultaProduto extends javax.swing.JFrame {

    static DaoProduto dao = new DaoProduto();

    /**
     * Creates new form ConsultaProduto
     */
    public ConsultaProduto() {
        initComponents();
        addProdutoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTipoBusca = new javax.swing.JComboBox<>();
        fieldBuscaPorFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultaProduto = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btneditaProduto = new javax.swing.JButton();
        lblConsultaProdutos = new javax.swing.JLabel();
        lblTipoBusca = new javax.swing.JLabel();
        lblbuscaID = new javax.swing.JLabel();

        setTitle("LOJA BONS PASSOS - CONSULTA PRODUTOS");
        setResizable(false);

        selectTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome" }));
        selectTipoBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectTipoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoBuscaActionPerformed(evt);
            }
        });

        fieldBuscaPorFiltro.setDragEnabled(true);

        tableConsultaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Marca", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableConsultaProduto);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btneditaProduto.setText("EDITAR");
        btneditaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditaProdutoActionPerformed(evt);
            }
        });

        lblConsultaProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultaProdutos.setText("CONSULTA DE PRODUTOS");

        lblTipoBusca.setText("Tipo de busca:");

        lblbuscaID.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(lblConsultaProdutos)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btneditaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoBusca)
                        .addGap(18, 18, 18)
                        .addComponent(selectTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblbuscaID)
                        .addGap(11, 11, 11)
                        .addComponent(fieldBuscaPorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoBusca)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldBuscaPorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(lblbuscaID)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btneditaProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectTipoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoBuscaActionPerformed
        // TODO add your handling code here:
        String[] opcoes = {"ID", "Nome"};
        if (selectTipoBusca.getSelectedItem().toString() == opcoes[0]) {
            lblbuscaID.setText("ID: ");

        } else if (selectTipoBusca.getSelectedItem().toString() == opcoes[1]) {
            lblbuscaID.setText("Nome: ");
        }
    }//GEN-LAST:event_selectTipoBuscaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        var filtro = selectTipoBusca.getSelectedItem().toString().toLowerCase();
        var valorBusca = fieldBuscaPorFiltro.getText();
        if (valorBusca.isBlank()) {
            addProdutoTable();
        } else {

            addProdutoTable(filtro, valorBusca);

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btneditaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditaProdutoActionPerformed

        int row = tableConsultaProduto.getSelectedRow();
        int idcolunmIndex = 0;

        Object idProduto = tableConsultaProduto.getValueAt(row, idcolunmIndex);

        EditaProduto telaEditaProduto = new EditaProduto();
        telaEditaProduto.setVisible(true);
        telaEditaProduto.preencheCampos((int) idProduto);


    }//GEN-LAST:event_btneditaProdutoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int row = tableConsultaProduto.getSelectedRow();
        int idcolunmIndex = 0;

        Produto produto = dao.buscaProdutoPorId(Integer.parseInt(tableConsultaProduto.getValueAt(row, idcolunmIndex).toString()));
        int op = JOptionPane.showConfirmDialog(rootPane, "Confirme a remoção do produto " + produto.getNomeProduto() + produto.getMarcaProduto(), "Remover Produto", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if (op == 0) {
            dao.removeProduto(produto);
            JOptionPane.showMessageDialog(rootPane, "Produto Removido com sucesso!", "Remoção concluida!", JOptionPane.INFORMATION_MESSAGE);
            addProdutoTable();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    public static void addProdutoTable() {
        DefaultTableModel model = (DefaultTableModel) tableConsultaProduto.getModel();
        model.setRowCount(0);
        List<Produto> produtos = dao.buscaProduto();

        for (Produto produto : produtos) {

            model.addRow(new Object[]{
                produto.getId(),
                produto.getNomeProduto(),
                produto.getMarcaProduto(),
                produto.getDepartamentoProd(),
                produto.getModeloProduto(),});
        }
    }

    public static void addProdutoTable(String selectFiltro, String valorFiltro) {
        DefaultTableModel model = (DefaultTableModel) tableConsultaProduto.getModel();
        model.setRowCount(0);
        List<Produto> produtos = new ArrayList<>();
        if (selectFiltro.equals("ID")) {

            produtos.add(dao.buscaProdutoPorId(Integer.parseInt(valorFiltro)));
        } else {
            produtos = dao.buscaProduto(selectFiltro, valorFiltro);
        }

        for (Produto produto : produtos) {

            model.addRow(new Object[]{
                produto.getId(),
                produto.getNomeProduto(),
                produto.getMarcaProduto(),
                produto.getDepartamentoProd(),
                produto.getModeloProduto()

            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btneditaProduto;
    private javax.swing.JTextField fieldBuscaPorFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultaProdutos;
    private javax.swing.JLabel lblTipoBusca;
    private javax.swing.JLabel lblbuscaID;
    private javax.swing.JComboBox<String> selectTipoBusca;
    private static javax.swing.JTable tableConsultaProduto;
    // End of variables declaration//GEN-END:variables
}
