/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bonsspassos.loja.consulta;

import com.bonsspassos.loja.daos.DaoCliente;
import com.bonsspassos.loja.edicao.EditaCliente;
import com.bonsspassos.loja.model.Cliente;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author FernandoBindandi
 */
public class ConsultaCliente extends javax.swing.JFrame {

    static DaoCliente dao = new DaoCliente();

    /**
     * Creates new form ConsultaCliente
     */
    public ConsultaCliente() {
        initComponents();
        addClienteTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaConsultaClientes = new javax.swing.JPanel();
        lblConsultaClientes = new javax.swing.JLabel();
        lblTipoBusca = new javax.swing.JLabel();
        boxTipoBusca = new javax.swing.JComboBox<>();
        lblBusca = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultaCliente = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btneditaCliente = new javax.swing.JButton();
        fieldBuscaPorFiltro = new javax.swing.JTextField();

        setTitle("CONSULTA CLIENTES");

        lblConsultaClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultaClientes.setText("CONSULTA DE CLIENTES");

        lblTipoBusca.setText("Tipo de busca:");

        boxTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF" }));
        boxTipoBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxTipoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoBuscaActionPerformed(evt);
            }
        });

        lblBusca.setLabelFor(fieldBuscaPorFiltro);
        lblBusca.setText("Digite o nome do cliente:");

        tableConsultaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableConsultaCliente);
        if (tableConsultaCliente.getColumnModel().getColumnCount() > 0) {
            tableConsultaCliente.getColumnModel().getColumn(0).setPreferredWidth(3);
            tableConsultaCliente.getColumnModel().getColumn(1).setPreferredWidth(16);
            tableConsultaCliente.getColumnModel().getColumn(2).setPreferredWidth(15);
            tableConsultaCliente.getColumnModel().getColumn(3).setMinWidth(59);
            tableConsultaCliente.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btneditaCliente.setText("EDITAR");
        btneditaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaConsultaClientesLayout = new javax.swing.GroupLayout(telaConsultaClientes);
        telaConsultaClientes.setLayout(telaConsultaClientesLayout);
        telaConsultaClientesLayout.setHorizontalGroup(
            telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaConsultaClientesLayout.createSequentialGroup()
                .addGroup(telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaConsultaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipoBusca)
                        .addGap(18, 18, 18)
                        .addComponent(boxTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaConsultaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBusca)
                        .addGap(18, 18, 18)
                        .addComponent(fieldBuscaPorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscar))
                    .addGroup(telaConsultaClientesLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblConsultaClientes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaConsultaClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btneditaCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        telaConsultaClientesLayout.setVerticalGroup(
            telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaConsultaClientesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblConsultaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBusca)
                    .addComponent(boxTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(btnBuscar)
                    .addComponent(fieldBuscaPorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(telaConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btneditaCliente))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(telaConsultaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(telaConsultaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void boxTipoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoBuscaActionPerformed
        // TODO add your handling code here:
        String[] opcoes = {"Nome", "CPF"};
        if (Objects.equals(boxTipoBusca.getSelectedItem().toString(), opcoes[0])) {
            lblBusca.setText("Digite o nome do cliente");

        } else if (Objects.equals(boxTipoBusca.getSelectedItem().toString(), opcoes[1])) {
            lblBusca.setText("Digite o CPF do cliente");
        }
    }//GEN-LAST:event_boxTipoBuscaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        var filtro = boxTipoBusca.getSelectedItem().toString().toLowerCase();
        var valorBusca = fieldBuscaPorFiltro.getText();
        if (valorBusca.isBlank()) {
            addClienteTable();
        } else {

            addClienteTable(filtro, valorBusca);
            fieldBuscaPorFiltro.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btneditaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditaClienteActionPerformed
        // TODO add your handling code here:

        int row = tableConsultaCliente.getSelectedRow();
        int idcolunmIndex = 0;

        Object idCliente = tableConsultaCliente.getValueAt(row, idcolunmIndex);

        EditaCliente telaEditaCliente = new EditaCliente();
        telaEditaCliente.setVisible(true);
        telaEditaCliente.preencheCampos((int) idCliente);
        addClienteTable();

    }//GEN-LAST:event_btneditaClienteActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int row = tableConsultaCliente.getSelectedRow();
        int idcolunmIndex = 0;

        Cliente cliente = dao.buscaClientePorId((int) tableConsultaCliente.getValueAt(row, idcolunmIndex));
        int op = JOptionPane.showConfirmDialog(rootPane, "Confirma a remoção do cliente " + cliente.getNome() + " CPF: " + cliente.getCpf() + "?", "Remover Cliente", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if (op == 0) {
            dao.removeCliente(cliente);
            JOptionPane.showMessageDialog(rootPane, "Cliente Removido com sucesso!", "Remoção concluida!", JOptionPane.INFORMATION_MESSAGE);
            addClienteTable();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    public static void addClienteTable() {
        DefaultTableModel model = (DefaultTableModel) tableConsultaCliente.getModel();
        model.setRowCount(0);
        List<Cliente> clientes = dao.buscaCliente();

        for (Cliente cliente : clientes) {

            model.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCpf(),
                cliente.getEmail()

            });

        }

    }

    public static void addClienteTable(String selectFiltro, String valorFiltro) {
        DefaultTableModel model = (DefaultTableModel) tableConsultaCliente.getModel();
        model.setRowCount(0);
        List<Cliente> clientes = dao.buscaCliente(selectFiltro, valorFiltro);
        ;
        for (Cliente cliente : clientes) {

            model.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCpf(),
                cliente.getEmail()

            });

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTipoBusca;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btneditaCliente;
    private javax.swing.JTextField fieldBuscaPorFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblConsultaClientes;
    private javax.swing.JLabel lblTipoBusca;
    private static javax.swing.JTable tableConsultaCliente;
    private javax.swing.JPanel telaConsultaClientes;
    // End of variables declaration//GEN-END:variables
}
